release-channel=@seed4j.release-channel@
seed4j-dependency-coordinate=@seed4j.group-id@:@seed4j.artifact-id@:@seed4j.version@
seed4j-upstream-commit=@seed4j.upstream-commit@
unavailable-modules=@seed4j.unavailable-modules@
