name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    if: github.repository == 'seed4j/seed4j-cli'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@978bb0b30c5ee8cdd332ced253758157150d43f0 # v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
